//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugsReporterServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int ID { get; set; }
        public string UserInfo { get; set; }
        public string Stack { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}
